### ISSUE TITLE
ClassNotFoundException in DictionaryProvider.php line 9

### ISSUE THREAD

**Issue by picks44** [KnpLabs/DictionaryBundle#25]
I'm trying to use the bundle but I have this Exception 
```
ClassNotFoundException in DictionaryProvider.php line 9:
Attempted to load class "Base" from namespace "Faker\Provider".
Did you forget a "use" statement for "Doctrine\ORM\Query\Expr\Base"?
```
I only installed the bundle like the doc said and configured it this way 

```
knp_dictionary:
    dictionaries:
        locales:
            type: 'key_value'
            content:
                "en": "EN"
                "fr_FR": "FR"
                "de": "DE"
                "es": "ES"
                "it": "IT"
                "pt": "PT"
                "zh": "ZH"
                "ru": "RU"
                "jp": "JP"
```
Nothing more, nothing less.
