### ISSUE TITLE
[RFC] Dictionary bundle 2.0

### ISSUE THREAD

**Issue by PedroTroller** [KnpLabs/DictionaryBundle#38]
- [ ] Configuration for LazyDictionary (service methods, invokable services, static methods)
- [x] Simple dictionary implementation
- [x] LazyDictionary for lazy loading
- [x] Remove `required` attribute into constaint
- [ ] Cached Dictionary (implement cache and backup)
- [ ] Update README

Feel free to propose other features.

**Comment by AntoineLelaisant** [comment]
What do you think about implement a inheritance management between dictionaries ?
for exemple:
```yml
payment:
    type: 'key_value'
    content:
        "card": "credit_card"
        "bank_transfert: "transfert"

payment_extended:
    parent: "payment"
    content:
        "discount": "discount"
```

- The dictionary `payment` would contain 2 item: `card` and `bank_transfert`
- The dictionary `payment_extended` whould contain 3 item: `card`, `bank transfert` & `discount`
