### ISSUE TITLE
Dictionary inheritance

### ISSUE THREAD

**Issue by AntoineLelaisant** [KnpLabs/DictionaryBundle#69]
I Just wanted to reopen the discussion about the possibility to create a inheritance system between dictionaries.

Already asked in #38 :

What do you think about implement a inheritance management between dictionaries ?
for exemple:

``` yml
payment:
    type: 'key_value'
    content:
        "card": "credit_card"
        "bank_transfert": "transfert"

payment_extended:
    parent: "payment"
    content:
        "discount": "discount"
```
- The dictionary `payment` would contain 2 item: `card` and `bank_transfert`
- The dictionary `payment_extended` whould contain 3 item: `card`, `bank transfert` & `discount`
