### ISSUE TITLE
Add a Cache decorator for any kind of dictionary

### ISSUE THREAD

**Issue by AntoineLelaisant** [KnpLabs/DictionaryBundle#99]
What about creating a configuration parameter that would allows to wrap the dictionary inside a `Cache` decorator ?

The config would looks like: 

```yaml
dictionaries:
    my_dictionary:
        type: key_value
        content:
            - foo: 'BAR'
            - bar: 'BAZ'
        cache: true
```

By default this parameter would be set to true, but when activated, it put the compiled content of the dictionary in the application cache. 

This is probably pointless with the example above but could make sense with combine or callable dictionaries.
